build:
	docker-compose up -d app

bash:
	docker-compose run --rm app bash

deploy:
	docker-compose run --rm app sls deploy --verbose

info:
	docker-compose run --rm app sls info

remove:
	docker-compose run --rm app sls remove