# For full config options, check the docs:
#    docs.serverless.com

service: personnel-sync

frameworkVersion: ^3.7.0

provider:
  name: aws
  runtime: go1.x
  stage: prod
  region: us-east-1
  timeout: 900
  versionFunctions: false
  memorySize: 128
  logRetentionInDays: 14
  iam:
    role:
      statements:
      - Effect: "Allow"
        Action:
        - "ses:SendEmail"
        Resource: "*"

package:
  patterns:
  - '!./**'
  - './bin/**'
  - './config.json'

functions:
  cron:
    handler: bin/personnelsync
    events:
    # cron(Minutes Hours Day-of-month Month Day-of-week Year)
    # Either `day-of-month` or `day-of-week` must be a question mark (?)
    - schedule: cron(10 * * * ? *) # every hour at 10 minutes after the hour
