# This is the configuration for goreleaser
# Check the documentation at http://goreleaser.com for details
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/lambda
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=lambda.norpc
gomod:
  proxy: true
