name: Test

on:
  push:
    branches:
    - "**"
    tags-ignore:
    - "*"

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.20 1.21 1.22 ]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: matrix.go-version

    - run: go test -v ./...
